version: '3.9'
services:
  influxdb:
    image: influxdb:2.1.1-alpine
    volumes:
      - influxdbv2:/var/lib/influxdb2
    ports:
      - "8086:8086"
    env_file:
      - ./.env
    entrypoint: ["./entrypoint.sh"]

  telegraf:
    image: telegraf:1.21.4-alpine
    user: telegraf:998
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    env_file:
      - ./.env
    depends_on:
      - influxdb

volumes:
  influxdbv2:
